# Generated by Django 3.1 on 2020-09-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic',
            name='name',
            field=models.CharField(default='pic', max_length=50),
            preserve_default=False,
        ),
    ]
